version: "3.7"

services:
  server:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      - FLOWLIB=/app/FlowLib/build/libJTFlowLav
      # - FLOWLIB=/app/FlowLib/build/libJTFlowCuda
    container_name: jt-flow
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./videos:/videos"
      - "./Server/index.mjs:/app/Server/index.mjs"
      - "/app/Server/ipfs"
      - "./Model:/app/Model"
    
    # entrypoint: /bin/bash
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
